version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  music-front_end:
    build: ./music_app
    ports:
      - "5173:5173"
    networks:
          - app-network

  ecommerce-front_end:
    build: ./ecommerce-app
    ports:
      - "5174:5174"

    networks:
      - app-network
